// Generated by CoffeeScript 2.7.0
(function() {
  var authModel, setup;

  authModel = require('../models/auth.coffee');

  setup = function(app) {
    app.post('/auth/send-code', async function(req, res) {
      var email, err, result;
      ({email} = req.body);
      if (!email) {
        return res.status(400).json({
          error: 'Email required'
        });
      }
      try {
        result = (await authModel.sendVerificationCode(email));
        return res.json(result);
      } catch (error) {
        err = error;
        console.error('Send code error:', err);
        return res.status(400).json({
          error: err.message
        });
      }
    });
    app.post('/auth/verify-code', async function(req, res) {
      var code, email, err, result;
      ({email, code} = req.body);
      if (!(email && code)) {
        return res.status(400).json({
          error: 'Email and code required'
        });
      }
      try {
        result = (await authModel.verifyCode(email, code));
        if (result.success) {
          req.session.email = email;
          req.session.authenticated = true;
          await new Promise(function(resolve, reject) {
            return req.session.save(function(err) {
              if (err) {
                return reject(err);
              } else {
                return resolve();
              }
            });
          });
          return res.json({
            success: true,
            email: email
          });
        } else {
          return res.status(400).json(result);
        }
      } catch (error) {
        err = error;
        console.error('Verify code error:', err);
        return res.status(500).json({
          error: 'Verification failed'
        });
      }
    });
    app.get('/auth/status', function(req, res) {
      var ref;
      if ((ref = req.session) != null ? ref.authenticated : void 0) {
        return res.json({
          authenticated: true,
          email: req.session.email
        });
      } else {
        return res.json({
          authenticated: false
        });
      }
    });
    return app.post('/auth/logout', function(req, res) {
      return req.session.destroy(function(err) {
        if (err) {
          console.error('Logout error:', err);
          return res.status(500).json({
            error: 'Logout failed'
          });
        }
        return res.json({
          success: true
        });
      });
    });
  };

  module.exports = {setup};

}).call(this);
