// Generated by CoffeeScript 2.7.0
(function() {
  var config, paymentService, rentModel, setup;

  paymentService = require('../services/payment.coffee');

  rentModel = require('../models/rent.coffee');

  config = require('../config.coffee');

  setup = function(app) {
    app.post('/payment/create-intent', async function(req, res) {
      var amount, amountDue, err, month, period, result, year;
      ({year, month, amount} = req.body);
      if (!(year && month && amount)) {
        return res.status(400).json({
          error: 'Year, month, and amount required'
        });
      }
      try {
        period = (await rentModel.getRentPeriod(year, month));
        if (!period) {
          return res.status(404).json({
            error: 'Rent period not found'
          });
        }
        amountDue = period.amount_due - (period.amount_paid || 0);
        if (Math.abs(amount - amountDue) > 0.01) {
          return res.status(400).json({
            error: 'Amount mismatch',
            expected: amountDue,
            requested: amount
          });
        }
        console.log(`Creating payment intent for ${req.session.email}: ${year}-${month}, amount: $${amount}`);
        result = (await paymentService.createPaymentIntent(amount, `Rent payment for ${year}-${String(month).padStart(2, '0')}`, {
          year,
          month,
          tenant: req.session.email
        }));
        console.log(`Payment intent created: ${result.id}`);
        return res.json(result);
      } catch (error) {
        err = error;
        console.error('Create payment intent error:', err);
        console.error('Error stack:', err.stack);
        return res.status(500).json({
          error: err.message
        });
      }
    });
    app.post('/payment/confirm', async function(req, res) {
      var err, month, paymentIntentId, result, year;
      ({paymentIntentId, year, month} = req.body);
      if (!(paymentIntentId && year && month)) {
        return res.status(400).json({
          error: 'Payment intent ID, year, and month required'
        });
      }
      try {
        console.log(`Confirming payment: ${paymentIntentId} for ${year}-${month}`);
        result = (await paymentService.confirmPayment(paymentIntentId, year, month));
        console.log(`Payment confirmed successfully: ${paymentIntentId}`);
        return res.json(result);
      } catch (error) {
        err = error;
        console.error('Confirm payment error:', err);
        console.error('Error details:', {
          paymentIntentId,
          year,
          month,
          message: err.message
        });
        return res.status(400).json({
          error: err.message
        });
      }
    });
    app.get('/payment/status/:paymentIntentId', async function(req, res) {
      var err, paymentIntentId, status;
      ({paymentIntentId} = req.params);
      try {
        status = (await paymentService.getPaymentStatus(paymentIntentId));
        return res.json(status);
      } catch (error) {
        err = error;
        console.error('Get payment status error:', err);
        return res.status(500).json({
          error: err.message
        });
      }
    });
    return app.post('/payment/setup-intent', async function(req, res) {
      var customer, err, result;
      try {
        customer = (await paymentService.getOrCreateCustomer(req.session.email, req.session.email.split('@')[0]));
        result = (await paymentService.createSetupIntent(customer.id));
        return res.json(Object.assign({}, result, {
          customerId: customer.id
        }));
      } catch (error) {
        err = error;
        console.error('Create setup intent error:', err);
        return res.status(500).json({
          error: err.message
        });
      }
    });
  };

  module.exports = {setup};

}).call(this);
