// Generated by CoffeeScript 2.7.0
(function() {
  var config, rentService, setup, workLogModel, workSessionModel;

  workLogModel = require('../models/work_log.coffee');

  workSessionModel = require('../models/work_session.coffee');

  rentService = require('../services/rent.coffee');

  config = require('../config.coffee');

  setup = function(app) {
    app.get('/work-logs', async function(req, res) {
      var allLogs, allSessions, err, i, j, k, len, len1, len2, limit, log, logs, project_id, ref, ref1, seen, session, sessions, traditionalLogs, uniqueLogs, w, worker, workerSessions;
      ({worker, project_id, limit} = req.query);
      try {
        if (worker) {
          sessions = (await workSessionModel.getAllSessions(worker));
        } else {
          allSessions = [];
          ref = config.WORKERS;
          for (i = 0, len = ref.length; i < len; i++) {
            w = ref[i];
            workerSessions = (await workSessionModel.getAllSessions(w));
            allSessions = allSessions.concat(workerSessions);
          }
          sessions = allSessions;
        }
        logs = [];
        for (j = 0, len1 = sessions.length; j < len1; j++) {
          session = sessions[j];
          if ((ref1 = session.status) === 'completed' || ref1 === 'cancelled') {
            log = (await workSessionModel.sessionToWorkLog(session));
            logs.push(log);
          }
        }
        traditionalLogs = (await workLogModel.getWorkLogs({
          worker,
          limit: 1000
        }));
        allLogs = logs.concat(traditionalLogs);
        uniqueLogs = [];
        seen = new Set();
        for (k = 0, len2 = allLogs.length; k < len2; k++) {
          log = allLogs[k];
          if (!seen.has(log.id)) {
            seen.add(log.id);
            uniqueLogs.push(log);
          }
        }
        uniqueLogs.sort(function(a, b) {
          return new Date(b.start_time) - new Date(a.start_time);
        });
        if (limit) {
          uniqueLogs = uniqueLogs.slice(0, parseInt(limit));
        }
        return res.json(uniqueLogs);
      } catch (error) {
        err = error;
        return res.status(500).json({
          error: err.message
        });
      }
    });
    app.post('/work-logs', async function(req, res) {
      var billable, description, duration, endDate, end_time, err, project_id, startDate, start_time, task_id, workLog, worker;
      ({worker, start_time, end_time, duration, description, billable, project_id, task_id} = req.body);
      if (!(worker && start_time && end_time && description)) {
        return res.status(400).json({
          error: 'Worker, start time, end time, and description required'
        });
      }
      if (!duration) {
        startDate = new Date(start_time);
        endDate = new Date(end_time);
        duration = Math.round((endDate - startDate) / 1000 / 60);
      }
      if (duration < 1) {
        return res.status(400).json({
          error: 'Work duration must be at least 1 minute'
        });
      }
      try {
        workLog = (await workLogModel.createWorkLog({
          worker: worker,
          start_time: start_time,
          end_time: end_time,
          duration: duration,
          description: description.trim(),
          project_id: project_id || null,
          task_id: task_id || null,
          billable: billable != null ? (billable ? 1 : 0) : 1,
          submitted: 0
        }));
        return res.json(workLog);
      } catch (error) {
        err = error;
        return res.status(500).json({
          error: err.message
        });
      }
    });
    app.put('/work-logs/:id', async function(req, res) {
      var billable, date, description, duration, end_time, err, existing, i, id, len, month, monthKey, months, ref, start_time, timestamp, updated, updates, worker, year;
      id = req.params.id;
      ({worker, start_time, end_time, duration, description, billable} = req.body);
      try {
        existing = (await workLogModel.getWorkLogById(id));
        if (!existing) {
          return res.status(404).json({
            error: 'Work log not found'
          });
        }
        updates = {};
        if (worker != null) {
          updates.worker = worker;
        }
        if (start_time != null) {
          updates.start_time = start_time;
        }
        if (end_time != null) {
          updates.end_time = end_time;
        }
        if (duration != null) {
          updates.duration = duration;
        }
        if (description != null) {
          updates.description = description.trim();
        }
        if (billable != null) {
          updates.billable = billable;
        }
        updated = (await workLogModel.updateWorkLog(id, updates));
        if (existing.worker === 'lyndzie' || updated.worker === 'lyndzie') {
          months = new Set();
          ref = [existing.start_time, updated.start_time];
          for (i = 0, len = ref.length; i < len; i++) {
            timestamp = ref[i];
            date = new Date(timestamp);
            months.add(`${date.getFullYear()}-${date.getMonth() + 1}`);
          }
          for (monthKey of months) {
            [year, month] = monthKey.split('-').map(function(n) {
              return parseInt(n);
            });
            await rentService.createOrUpdateRentPeriod(year, month);
          }
        }
        return res.json(updated);
      } catch (error) {
        err = error;
        return res.status(500).json({
          error: err.message
        });
      }
    });
    return app.delete('/work-logs/:id', async function(req, res) {
      var date, err, existing, id, month, year;
      id = req.params.id;
      try {
        existing = (await workLogModel.getWorkLogById(id));
        if (!existing) {
          return res.status(404).json({
            error: 'Work log not found'
          });
        }
        await workLogModel.deleteWorkLog(id);
        if (existing.worker === 'lyndzie') {
          date = new Date(existing.start_time);
          year = date.getFullYear();
          month = date.getMonth() + 1;
          await rentService.createOrUpdateRentPeriod(year, month);
        }
        return res.json({
          success: true,
          deleted: id
        });
      } catch (error) {
        err = error;
        return res.status(500).json({
          error: err.message
        });
      }
    });
  };

  module.exports = {setup};

}).call(this);
