# This workflow will install Deno then build and test the application.
# Linting is performed locally via pre-push git hook.
# Tests run only if test files are present.
# For more information see: https://github.com/denoland/setup-deno

name: Deno CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build application
        run: deno task build

      - name: Check for tests
        id: check_tests
        run: |
          if find . -name "*_test.ts" -o -name "*_test.js" -o -name "*.test.ts" -o -name "*.test.js" | grep -q .; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests
        if: steps.check_tests.outputs.has_tests == 'true'
        run: deno test -A
